### ISSUE TITLE
litmus tests fail

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis-reva#18] opened 2020-01-21 11:04 UTC
`docker run -e LITMUS_URL="http://172.17.0.1:9140/remote.php/webdav" -e LITMUS_USERNAME="einstein" -e LITMUS_PASSWORD="relativity" -e TESTS="<test-scope>"  owncloud/litmus:latest`

### basic
```
-> running `basic':
 0. init.................. pass
 1. begin................. pass
 2. options............... pass
 3. put_get............... pass
 4. put_get_utf8_segment.. pass
 5. put_no_parent......... pass
 6. mkcol_over_plain...... pass
 7. delete................ pass
 8. delete_null........... pass
 9. delete_fragment....... pass
10. mkcol................. pass
11. mkcol_again........... pass
12. delete_coll........... pass
13. mkcol_no_parent....... pass
14. mkcol_with_body....... pass
15. finish................ pass
<- summary for `basic': of 16 tests run: 16 passed, 0 failed. 100.0%

```
### copymove
```
-> running `copymove':
 0. init.................. pass
 1. begin................. pass
 2. copy_init............. pass
 3. copy_simple........... pass
 4. copy_overwrite........ pass
 5. copy_nodestcoll....... pass
 6. copy_cleanup.......... pass
 7. copy_coll............. pass
 8. copy_shallow.......... WARNING: Could not delete csrc
WARNING: Could not clean up cdest
    ...................... pass (with 2 warnings)
 9. move.................. FAIL (MOVE `/remote.php/webdav/litmus/move' to `/remote.php/webdav/litmus/movedest': 500 Internal Server Error)
10. move_coll............. FAIL (collection MOVE `/remote.php/webdav/litmus/mvsrc/' to `/remote.php/webdav/litmus/mvdest/': 500 Internal Server Error)
11. move_cleanup.......... pass
12. finish................ pass
<- summary for `copymove': of 13 tests run: 11 passed, 2 failed. 84.6%
-> 2 warnings were issued.
````

### props
```
-> running `props':
 0. init.................. pass
 1. begin................. pass
 2. propfind_invalid...... pass
 3. propfind_invalid2..... pass
 4. propfind_d0........... pass
 5. propinit.............. pass
 6. propset............... pass
 7. propget............... pass
 8. propextended.......... pass
 9. propmove.............. FAIL (MOVE `/remote.php/webdav/litmus/prop' to `/remote.php/webdav/litmus/prop2': 500 Internal Server Error)
10. propget............... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop': 404 Not Found)
11. propdeletes........... FAIL (PROPPATCH on `/remote.php/webdav/litmus/prop': 404 Not Found)
12. propget............... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop': 404 Not Found)
13. propreplace........... FAIL (PROPPATCH on `/remote.php/webdav/litmus/prop': 404 Not Found)
14. propget............... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop': 404 Not Found)
15. propnullns............ FAIL (PROPPATCH of property with null namespace (see FAQ))
16. propget............... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop': 404 Not Found)
17. propremoveset......... FAIL (PROPPATCH remove then set)
18. propget............... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop': 404 Not Found)
19. propsetremove......... FAIL (PROPPATCH remove then set)
20. propget............... FAIL (PROPFIND on `/remote.php/webdav/litmus/prop': 404 Not Found)
21. propvalnspace......... FAIL (PROPPATCH of property with value defining namespace)
22. propwformed........... pass
23. propinit.............. pass
24. propmanyns............ pass
25. propget............... pass
26. propcleanup........... pass
27. finish................ pass
<- summary for `props': of 28 tests run: 15 passed, 13 failed. 53.6%
See debug.log for network/debug traces.
```

### locks
```
-> running `locks':
 0. init.................. pass
 1. begin................. pass
 2. options............... pass
 3. precond............... pass
 4. init_locks............ pass
 5. put................... pass
 6. lock_excl............. pass
 7. discover.............. pass
 8. refresh............... pass
 9. notowner_modify....... FAIL (DELETE of locked resource should fail)
10. notowner_lock......... FAIL (LOCK on locked resource)
11. owner_modify.......... FAIL (PROPPATCH on locked resouce on `/remote.php/webdav/litmus/lockme': 207 Multi-Status)
12. notowner_modify....... FAIL (DELETE of locked resource should fail)
13. notowner_lock......... FAIL (LOCK on locked resource)
14. copy.................. FAIL (could not COPY locked resource:
404 Not Found)
15. cond_put.............. SKIPPED
16. fail_cond_put......... SKIPPED
17. cond_put_with_not..... pass
18. cond_put_corrupt_token FAIL (conditional PUT with invalid lock-token should fail: 204 No Content)
19. complex_cond_put...... pass
20. unlock................ FAIL (UNLOCK on `/remote.php/webdav/litmus/lockme': 501 Not Implemented)
21. fail_cond_put_unlocked FAIL (conditional PUT with invalid lock-token should fail: 204 No Content)
22. lock_shared........... FAIL (requested lockscope not satisfied!  got shared, wanted exclusive)
23. notowner_modify....... SKIPPED
24. notowner_lock......... SKIPPED
25. owner_modify.......... SKIPPED
26. double_sharedlock..... SKIPPED
27. notowner_modify....... SKIPPED
28. notowner_lock......... SKIPPED
29. unlock................ SKIPPED
30. prep_collection....... pass
31. lock_collection....... pass
32. owner_modify.......... FAIL (PROPPATCH on locked resouce on `/remote.php/webdav/litmus/lockcoll/lockme.txt': 207 Multi-Status)
33. notowner_modify....... FAIL (DELETE of locked resource should fail)
34. refresh............... pass
35. indirect_refresh...... pass
36. unlock................ FAIL (UNLOCK on `/remote.php/webdav/litmus/lockcoll/': 501 Not Implemented)
37. unmapped_lock......... See debug.log for network/debug traces.
Segmentation fault (core dumped)
```

### http
```
-> running `http':
 0. init.................. pass
 1. begin................. pass
 2. expect100............. pass
 3. finish................ pass
<- summary for `http': of 4 tests run: 4 passed, 0 failed. 100.0%
```

**Comment by PVince81** [comment] 2020-05-04 08:46
likely related sub-issues: https://github.com/owncloud/ocis-reva/issues/165 and https://github.com/owncloud/ocis-reva/issues/163

let's rerun the litmus test after these are merged

**Comment by PVince81** [comment] 2020-05-04 13:08
Seems I'm unable to run the litmus tests due to basic auth not working:
```
docker run -e LITMUS_URL="http://172.17.0.1:9140/remote.php/webdav/home" -e LITMUS_USERNAME="einstein" -e LITMUS_PASSWORD="relativity" -e TESTS="basic" owncloud/litmus:latest
-> running `basic':
 0. init.................. pass
 1. begin................. FAIL (Could not create new collection `/remote.php/webdav/home/litmus/' for tests: 401 Unauthorized
Server must allow `MKCOL /remote.php/webdav/home/litmus/' for tests to proceed)
<- summary for `basic': of 2 tests run: 1 passed, 1 failed. 50.0%
See debug.log for network/debug traces.
```

I noticed that with the LDAP test setup also only the API acceptance tests run, probably they use another auth method (openidconnect I guess) and not basic auth.

Not sure if more is needed for the setup or if I missed something from the docs.
The reva-auth-basic service is running.

Anyway, I think we could rerun the tests as I think the 500 status codes should be gone now.

**Comment by individual-it** [comment] 2020-05-05 08:33
@PVince81 `/home` is obsolete see https://github.com/owncloud/ocis-reva/pull/77
I've updated the issue post

**Comment by individual-it** [comment] 2020-05-05 08:38
I've also updated the results, most test do have better results, but funny that `locks` now ends with an `Segmentation fault (core dumped)`

P.S. `basic` and `http` already run in CI see #120 & #121

**Comment by PVince81** [comment] 2020-05-05 13:07
Shallow COPY raised here: https://github.com/owncloud/ocis-reva/issues/171

**Comment by PVince81** [comment] 2020-05-06 08:48
I can't reproduce the "propfind_d0" case locally: a PROPFIND with Depth 0 does return a correct result for me:
```
% curl -H "Depth: 0" -X PROPFIND -u einstein:relativity http://localhost:9140/remote.php/webdav/litmus/ | xmllint --format -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   854  100   854    0     0  27548      0 --:--:-- --:--:-- --:--:-- 27548
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/webdav/litmus/</d:href>
    <d:propstat>
      <d:prop>
        <oc:id>MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTYyOmI2MjBlY2E1LTNlMTMtNGQyZi04ZDcwLWY1NzdkMzJlYWU1Zg==</oc:id>
        <oc:fileid>MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTYyOmI2MjBlY2E1LTNlMTMtNGQyZi04ZDcwLWY1NzdkMzJlYWU1Zg==</oc:fileid>
        <d:getetag>"0e97b1eba6b58a114de01f0513bc7daf"</d:getetag>
        <oc:permissions>WCKDNVR</oc:permissions>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:getcontenttype>httpd/unix-directory</d:getcontenttype>
        <oc:size>30</oc:size>
        <d:getlastmodified>Wed, 06 May 2020 08:12:07 UTC</d:getlastmodified>
        <oc:favorite>0</oc:favorite>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```
I've diffed the first member result from the Depth: 1 request with Depth: 0 and they are identical.

**Comment by individual-it** [comment] 2020-05-06 09:04
request and response of the litmus test look like (catched with wireshark):
```
PROPFIND /remote.php/webdav/litmus/ HTTP/1.1
User-Agent: litmus/0.13 neon/0.29.6
Connection: TE
TE: trailers
Host: 172.17.0.1:9140
Depth: 0
Content-Length: 304
Content-Type: application/xml
Authorization: Basic ZWluc3RlaW46cmVsYXRpdml0eQ==
X-Litmus: props: 4 (propfind_d0)

<?xml version="1.0" encoding="utf-8"?>
<propfind xmlns="DAV:"><prop>
<getcontentlength xmlns="DAV:"/>
<getlastmodified xmlns="DAV:"/>
<displayname xmlns="DAV:"/>
<resourcetype xmlns="DAV:"/>
<foo xmlns="http://example.com/neon/litmus/"/>
<bar xmlns="http://example.com/neon/litmus/"/>
</prop></propfind>
HTTP/1.1 207 Multi-Status
Access-Control-Allow-Origin: *
Content-Type: application/xml; charset=utf-8
Dav: 1, 3, extended-mkcol
Vary: Origin
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTg4NzU5MDg5LCJpYXQiOjE1ODg3NTU0ODksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTk5OCIsInVzZXIiOnsiaWQiOnsiaWRwIjoiaHR0cDovL2xvY2FsaG9zdDo5OTk4Iiwib3BhcXVlX2lkIjoiNGM1MTBhZGEtYzg2Yi00ODE1LTg4MjAtNDJjZGY4MmMzZDUxIn0sInVzZXJuYW1lIjoiZWluc3RlaW4iLCJtYWlsIjoiZWluc3RlaW5AZXhhbXBsZS5vcmciLCJkaXNwbGF5X25hbWUiOiJBbGJlcnQgRWluc3RlaW4iLCJncm91cHMiOlsic2FpbGluZy1sb3ZlcnMiLCJ2aW9saW4taGF0ZXJzIiwicGh5c2ljcy1sb3ZlcnMiXX19.LSOHE5yAJ_nULwWuo6Z4ap6G-CKsbqoe7XT_MHGejAA
Date: Wed, 06 May 2020 08:58:09 GMT
Content-Length: 720

<?xml version="1.0" encoding="utf-8"?><d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/webdav/litmus/</d:href><d:propstat><d:prop><d:getlastmodified>Wed, 06 May 2020 08:58:09 UTC</d:getlastmodified><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength></d:getcontentlength><d:displayname></d:displayname><http://example.com/neon/litmus/:foo></http://example.com/neon/litmus/:foo><http://example.com/neon/litmus/:bar></http://example.com/neon/litmus/:bar></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>
```
I will investigate what litmus expects as response

**Comment by PVince81** [comment] 2020-05-06 09:09
> I will investigate what litmus expects as response

once we know please make a separate ticket with expected result so we can process it and fix it.
thanks

**Comment by PVince81** [comment] 2020-05-06 09:20
@individual-it you don't need to research further, it's the namespace issue:
```
<http://example.com/neon/litmus/:foo></http://example.com/neon/litmus/:foo>
```

same as https://github.com/owncloud/ocis-reva/issues/57#issuecomment-624523683

**Comment by PVince81** [comment] 2020-05-06 13:10
regarding "move_coll", I looked at the source code and its setup requires a working COPY + depth:infinity, which we don't have until https://github.com/owncloud/ocis-reva/issues/173 is merged.

**Comment by PVince81** [comment] 2020-05-07 11:21
raised https://github.com/owncloud/ocis-reva/issues/182 for further litmus issues with copy

**Comment by PVince81** [comment] 2020-05-07 11:23
raised https://github.com/owncloud/ocis-reva/issues/183 for further issues with props

**Comment by PVince81** [comment] 2020-05-13 08:02
Closing in favor of:

- copymove issues: https://github.com/owncloud/ocis-reva/issues/182
- LOCKs issue: https://github.com/owncloud/ocis-reva/issues/172
- props issue: https://github.com/owncloud/ocis-reva/issues/183

I'll add an update of the test results in the respective tickets

**Closed by PVince81** 2020-05-13 08:02 UTC
Labels: bug

**Comment by PVince81** [comment] 2020-05-20 09:32
PR to tidy up tests in core: https://github.com/owncloud/core/pull/37419
